name: Deploy Lambda

on:
  push:
    branches:
      #- main
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download from Artifactory
        run: |
          curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD \
          -O "https://artifactory.example.com/artifactory/my-repo/lambda_function.zip"
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve