name: Deploy on Lambda

on:
    workflow_run:
      workflows: ["lambda-ci.yml"]  # Name of the first workflow
      types:
        - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Install tflint
        run: |
            wget --quiet https://github.com/terraform-linters/tflint/releases/download/v0.51.2/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
            mv tflint /usr/local/bin
      #- name: Run TFLint
        #run: tflint --config .tflint.hcl || exit 1               
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
